source 'ssh://gitlab.finogeeks.club/finclip-ios/FinPods'
source 'https://cdn.cocoapods.org/'

target 'iOS-Objc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-Objc
  pod 'FinClipChatKit'

end
